---
apiVersion: v1
kind: Namespace
metadata:
  name: nodejs-app-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: nodejs-app-namespace
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: "skkumar97260/sk-image:latest"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: nodejs-app-namespace
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80        # Exposing the service externally on port 80
      targetPort: 3000 # Targeting the container's port 3000
  type: ClusterIP   # Internal Kubernetes service

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-app-ingress
  namespace: nodejs-app-namespace
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing # Exposing the Ingress to the internet
    alb.ingress.kubernetes.io/target-type: ip          # Target IP mode for routing to pods directly
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]' # Listen on port 80 for HTTP
    alb.ingress.kubernetes.io/backend-protocol: HTTP   # Backend protocol for communication with pods
    alb.ingress.kubernetes.io/subnets: "subnet-01ef1e4073ed088a0,subnet-0af953e1e6b57bccd,subnet-0ed57ae70b49e0a46,subnet-078a1ea5bdb97fdcc" # AWS subnets for ALB
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nodejs-app
              port:
                number: 80  # The service exposes port 80 externally
