apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-app-hpa
  namespace: nodejs-app-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-app  # The name of the deployment this HPA is scaling
  minReplicas: 1       # Minimum number of replicas (pods)
  maxReplicas: 10      # Maximum number of replicas (pods)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Target CPU utilization (70% in this case)
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70  # Target memory utilization (70% in this case)
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30  # Wait 30 seconds before scaling up again
      policies:
        - type: Pods
          value: 1  # Scale up by 1 pod at a time
          periodSeconds: 30  # Check every 30 seconds
    scaleDown:
      stabilizationWindowSeconds: 30  # Wait 30 seconds before scaling down again
      policies:
        - type: Pods
          value: 1  # Scale down by 1 pod at a time
          periodSeconds: 30  # Check every 30 seconds
