apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: nodejs-app-namespace
spec:
  type: ClusterIP
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
