apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: kube-system
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  
